version: 2.9.8.{build}
os: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '2.9.8'
  assembly_file_version: '2.9.8'
  assembly_informational_version: '2.9.8'
before_build:
- cmd: nuget restore
build:
  project: linq2db.LINQPad.sln
  verbosity: minimal
after_build:
- cmd: xcopy Source\linq2db.LINQPad.lpx .\ /y
- cmd: xcopy Source\linq2db.LINQPad.lpx6 .\ /y

artifacts:
- path: linq2db.LINQPad.lpx
  name: linq2db.LINQPad Driver
- path: linq2db.LINQPad.lpx6
  name: linq2db.LINQPad 6 Driver

deploy:
  provider: FTP
  protocol: ftp
  host: tkachev.com
  username: linq2db
  folder: /
  password:
    secure: rnYQ08pwgvUSkuRhHDndvw==
  on:
    branch: release
